// frontend/src/shared/components/Pagination/index.tsx
import { ReactComponent as Arrow } from 'assets/img/arrow.svg';
import { MoviePage } from 'shared/types/movie';
import './styles.css';

type Props = {
    page: MoviePage;
    onChange: Function;
}

function Pagination ({ page, onChange} : Props) {

    return (
        <div className="movie-pagination-container">
            <div className="movie-pagination-box">

                <button className="movie-pagination-button" 
                    disabled={page.first} 
                    onClick={() => onChange(page.number - 1)}
                >
                    <Arrow />
                </button>

                <p>{`${page.number + 1} de ${page.totalPages}`}</p>

                <button className="movie-pagination-button" 
                    disabled={page.last} 
                    onClick={() => onChange(page.number + 1)}
                >
                    <Arrow className="movie-flip-horizontal" />
                </button>
                
            </div>
        </div>
    )
}

export default Pagination ;

// frontend-app/src/app/shared/components/pagination/pagination.component.ts

import { Component, EventEmitter, Input, Output } from '@angular/core';
import { MoviePage } from '@app/shared/models/movie-page';

@Component({
  selector: 'app-pagination',
  templateUrl: './pagination.component.html',
  styleUrls: ['pagination.component.css']
})
export class PaginationComponent {

  @Input()
  page = {} as MoviePage;  

  @Output()
  status: EventEmitter<any> = new EventEmitter();

  changePage(value: number): void {    
    this.status.emit((this.page.number + value) as number);
  } 

}

<div class="movie-pagination-container">
    <div class="movie-pagination-box">

        <button class="movie-pagination-button" 
            [disabled]="page.first"
            (click)="changePage(-1)"
        >
            <img src="@app/../assets/img/arrow.svg" 
                alt="arrow left"
            />        
        </button>

        <p>{{page.number + 1}} de {{page.totalPages}}</p>

        <button 
            class="movie-pagination-button" 
            [disabled]="page.last"
            (click)="changePage(1)"
        >        
        <img 
            class="movie-flip-horizontal" 
            src="@app/../assets/img/arrow.svg" 
            alt="arrow right"
        />
        </button>
    </div>
</div>
