// frontend-app/src/app/shared/components/movie-card/movie-card.component.ts
import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';

import { Movie } from '@app/shared/models/movie';


@Component({
  selector: 'app-movie-card',
  templateUrl: './movie-card.component.html'
})
export class MovieCardComponent {

  @Input()
  movie = {} as Movie; 

  constructor(
    private router: Router,
  ) { }  

  avaliar(id: number): void {
    if (id) this.router.navigate([`/movie-form/${id}`]);    
  }

}

<div>
    <img class="movie-movie-card-image"src="{{movie.image}}" alt="{{movie.image}}">
    <div class="movie-card-bottom-container">
        <h3>{{movie.title}}</h3>
        
        <app-movie-score 
            [count]="movie.count"
            [score]="movie.score">
        </app-movie-score>        

        <div class="btn btn-primary movie-btn" (click)="avaliar(movie.id)">Avaliar</div>
    </div>
</div>

// frontend/src/shared/components/MovieCard/index.tsx
import { Link } from 'react-router-dom';
import { Movie } from 'shared/types/movie';
import MovieScore from '../MovieScore';


type Props = {
  movie: Movie
}

function MovieCard( { movie } : Props) {

  return (
    <div>
      <img className="movie-movie-card-image" src={movie.image} alt={movie.title} />
      <div className="movie-card-bottom-container">
          <h3>{movie.title}</h3>
          <MovieScore count={movie.count} score={movie.score} />

          <Link to={`/form/${movie.id}`} >
           <div className="btn btn-primary movie-btn">Avaliar</div>
          </Link>

      </div>
    </div>
  );
}

export default MovieCard;
