// frontend/src/shared/components/MovieScore/index.tsx
import MovieStars from "../MovieStars";
import './styles.css';

function MovieScore() {

    const score = 3.5;
    const count = 13;

    return (
        <div className="movie-score-container">
            <p className="movie-score-value">{score > 0 ? score.toFixed(1) : '-'}</p>
            <MovieStars />
            <p className="movie-score-count">{count} avaliações</p>
        </div>      
    );
}

export default MovieScore;

// frontend-app/src/app/shared/components/movie-score/movie-score.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-movie-score',
  templateUrl: './movie-score.component.html',
  styleUrls: ['./movie-score.component.css']
})
export class MovieScoreComponent implements OnInit {

  @Input()
  score: any;

  @Input()
  count: number = 10;  

  ngOnInit(): void {
    this.fixNumber();
  }

  fixNumber(): void {
    this.score = this.score > 0 ? this.score.toFixed(1) : '-';
  }

}

<div class="movie-score-container">
    <p class="movie-score-value">{{score}}</p>
    
    <app-movie-stars [score]="score"></app-movie-stars>
    
    <p class="movie-score-count">{{count}} avaliações</p>
</div>
