// frontend/src/shared/components/MovieStars/index.tsx
import { ReactComponent as StarFull } from 'assets/img/star-full.svg';
import { ReactComponent as StarHalf } from 'assets/img/star-half.svg';
import { ReactComponent as StarEmpty } from 'assets/img/star-empty.svg';
import './styles.css';

type Props = {
  score: number;
}

type StarProps = {
  fill: number;
}


function getFills(score: number) {

  const fills = [0, 0, 0, 0, 0];

  const integerPart = Math.floor(score);

  for (let i = 0; i < integerPart; i++) {
    fills[i] = 1;
  }

  const diff = score - integerPart;
  if (diff > 0) {
    fills[integerPart] = 0.5;
  }

  return fills;
}


function Star({ fill } : StarProps) {
  if (fill === 0) {
    return <StarEmpty />
  }
  else if (fill === 1) {
    return <StarFull />
  }
  else {
    return <StarHalf />
  }
}

function MovieStars({ score } : Props) {

  const fills = getFills(score);

  return (
    <div className="movie-stars-container">
      <Star fill={fills[0]} />
      <Star fill={fills[1]} />
      <Star fill={fills[2]} />
      <Star fill={fills[3]} />
      <Star fill={fills[4]} />
    </div>
  );
}

export default MovieStars;

// frontend-app/src/app/shared/components/movie-stars/movie-stars.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-movie-stars',
  templateUrl: './movie-stars.component.html',
  styleUrls: ['movie-stars.component.css']
})
export class MovieStarsComponent implements OnInit {

  @Input()
  score: number = 0;

  fills: number[] = [];
  fill: number = 0;  

  ngOnInit(): void {
    this.fills = this.getFills(this.score);    
  }

  private getFills(score: number): number[] {

    const fills = [0, 0, 0, 0, 0];

    const integerPart = Math.floor(score);

    for (let i = 0; i < integerPart; i++) {
      fills[i] = 1;
    }

    const diff = score - integerPart;
    if (diff > 0) {
      fills[integerPart] = 0.5;
    }

    return fills;
  }

}

<div class="movie-stars-container">        
    <app-star [fill]="fills[0]"></app-star>
    <app-star [fill]="fills[1]"></app-star>
    <app-star [fill]="fills[2]"></app-star>
    <app-star [fill]="fills[3]"></app-star>
    <app-star [fill]="fills[4]"></app-star>
</div>
